version: "3"
  
services:
  sonarqube:
    image: sonarqube:8.7-community
    container_name: sonarqube
    hostname: sonarqube
    restart: always
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar_admin
      - sonar.jdbc.password=sonar_password
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
      - SONAR_SECURITY_REALM=LDAP
      - ldap.url=LDAPURL
      - ldap.bindDn=CN=AD Query,CN=Managed,DC=my,DC=company,DC=local
      - ldap.bindPassword=xSECRETx
      - ldap.user.baseDn=OU=Test Bench Users,DC=my,DC=company,DC=local
      - ldap.user.request= (&(objectClass=person)(sAMAccountName={login}))
    volumes:
      - /etc/sonarqube/logs:/opt/sonarqube/logs
      - /etc/sonarqube/data:/opt/sonarqube/data
      - /etc/sonarqube/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:13.1
    container_name: db
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=sonar_db_admin
      - POSTGRES_PASSWORD=sonar_db_password
    volumes:
      - pg_db:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  pg_db:
    driver: local
  pg_data:
    driver: local